name: SolidityAuditing
channels:
  - defaults
dependencies:
  - ca-certificates=2025.2.25=hca03da5_0
  - libcxx=14.0.6=h848a8c0_0
  - libffi=3.4.4=hca03da5_1
  - ncurses=6.4=h313beb8_0
  - openssl=3.0.16=h02f6b3c_0
  - python=3.9.21=hb885b13_1
  - readline=8.2=h1a28f6b_0
  - sqlite=3.45.3=h80987f9_0
  - tk=8.6.14=h6ba3021_0
  - tzdata=2025a=h04d1e81_0
  - wheel=0.45.1=py39hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.2.13=h18a0788_1
  - pip:
      - aiohappyeyeballs==2.5.0
      - aiohttp==3.11.13
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.13.2
      - async-timeout==5.0.1
      - attrs==25.1.0
      - bitarray==3.1.1
      - brownie==0.5.1
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - ckzg==2.0.1
      - cytoolz==1.0.1
      - eth-abi==5.2.0
      - eth-account==0.13.5
      - eth-hash==0.7.1
      - eth-keyfile==0.8.1
      - eth-keys==0.6.1
      - eth-rlp==2.2.0
      - eth-typing==5.2.0
      - eth-utils==5.2.0
      - frozenlist==1.5.0
      - hexbytes==1.3.0
      - idna==3.10
      - multidict==6.1.0
      - parsimonious==0.10.0
      - pip==25.0.1
      - propcache==0.3.0
      - pycryptodome==3.21.0
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pyunormalize==16.0.0
      - pyyaml==5.3.1
      - regex==2024.11.6
      - requests==2.32.3
      - rlp==4.1.0
      - setuptools==77.0.3
      - toolz==1.0.0
      - types-requests==2.32.0.20250306
      - typing-extensions==4.12.2
      - urllib3==2.3.0
      - web3==7.8.0
      - websockets==13.1
      - yarl==1.18.3
